# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: opensecurity/mobile-security-framework-mobsf

    working_directory: ~/repo

    steps:
      #- run: docker pull mcr.microsoft.com/playwright:bionic
      #- run: docker run -it --rm --ipc=host mcr.microsoft.com/playwright:bionic /bin/bash
          
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          

      # run tests!
      - run: pwd
      - run: ls
      - run: npm install
      - run: node playwright.js