version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: opensecurity/mobile-security-framework-mobsf

    working_directory: ~/repo

    steps:
      - checkout    
      # run commands!
      - run: pwd
      - run: ls
      #- run: curl --help

