version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: opensecurity/mobile-security-framework-mobsf

    working_directory: ~/repo

    steps:
      - checkout 
      - setup_remote_docker:
          docker_layer_caching: true
      # run commands!
      - run: pwd
      - run: ls
      #- run: curl --help
      - run: echo "MobSF_Key=$MobSF_Key" > env.list
      - run: docker run -it --env-file ./env.list -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest

