version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      image: opensecurity/mobile-security-framework-mobsf
      #image: ubuntu-1604:202007-01

    working_directory: ~/repo

    steps:
      - checkout 
      #- setup_remote_docker
      # run commands!
      - run: pwd
      - run: ls
      #- run: curl --help
      - run: echo "MobSF_Key=$MobSF_Key" > env.list
      #- run: docker pull opensecurity/mobile-security-framework-mobsf
      - run: ls
      #- run: docker run -it --rm -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest
      - run: cd /root/Mobile-Security-Framework-MobSF/scripts
      #- run: curl -F '~/apks/pivaa.apk' http://localhost:8000/api/v1/upload -H "Authorization:$MobSF_Key"

